/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be :

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.
*/

#include <stdio.h>

#define MAXRANGE 4000000

void main()
{
	int soma = 0;
	int proximo = 0;
	int corrente = 1;
	int anterior = 0;
	/// calcular fribronacci brute force.. 

	do 
	{
		proximo = corrente + anterior;
		if ((proximo % 2) == 0)
		{
			soma += proximo;
		}	
		printf(" %d %d \n", proximo, soma);
		anterior = corrente; 
		corrente = proximo;
	} while (corrente < MAXRANGE);
	getchar();

}